#!/usr/bin/env python3
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "docs/product/capabilities.yaml"
OUTPUT = ROOT / "docs/product/current-capability-status.md"

LABELS = {
    "not_started": "Not started",
    "stubbed": "Stubbed / trust boundary",
    "implemented_prototype": "Implemented prototype",
    "integration_tested": "Integration-tested",
    "deployed_validated": "Deployed and validated",
    "assessed_approved": "Assessed / approved",
    "production_ready": "Production-ready",
}

def load_registry():
    with REGISTRY.open(encoding="utf-8") as handle:
        data = json.load(handle)
    if data.get("schema_version") != 1:
        raise ValueError("unsupported capability registry schema")
    seen = set()
    for capability in data.get("capabilities", []):
        capability_id = capability.get("id", "")
        if not capability_id or capability_id in seen:
            raise ValueError(f"missing or duplicate capability id: {capability_id!r}")
        seen.add(capability_id)
        status = capability.get("status")
        if status not in LABELS:
            raise ValueError(f"{capability_id}: unknown status {status!r}")
        for field in ("implementation_evidence", "test_evidence", "external_evidence"):
            for evidence in capability.get(field, []):
                if not (ROOT / evidence).exists():
                    raise ValueError(f"{capability_id}: missing evidence path {evidence}")
        if status == "production_ready" and not capability.get("external_evidence"):
            raise ValueError(f"{capability_id}: production-ready requires external evidence")
        if not capability.get("owner") or not capability.get("last_verified_commit"):
            raise ValueError(f"{capability_id}: owner and last_verified_commit are required")
    return data

def render(data):
    lines = [
        "# Current capability status",
        "",
        "<!-- Generated by scripts/generate-capability-status.py; edit capabilities.yaml instead. -->",
        "",
        "This table uses the strict vocabulary defined in `capabilities.yaml`. Repository evidence proves code or disposable integration behaviour; it does not substitute for deployment, assessment, or approval evidence.",
        "",
        "| Capability | Status | Repository evidence | Remaining gaps | Owner |",
        "|---|---|---|---|---|",
    ]
    for item in data["capabilities"]:
        evidence = item["implementation_evidence"] + item["test_evidence"] + item["external_evidence"]
        links = ", ".join(f"[`{Path(path).name}`](../../{path})" for path in evidence) or "None"
        gaps = item["remaining_gaps"].replace("|", "\\|")
        lines.append(f"| {item['name']} | {LABELS[item['status']]} | {links} | {gaps} | {item['owner']} |")
    lines += [
        "",
        "Terms such as production, durable, ready, implemented, or validated describe a scoped target unless the registry status and linked evidence prove that maturity level.",
        "",
    ]
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated Markdown is stale")
    args = parser.parse_args()
    try:
        rendered = render(load_registry())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"capability registry invalid: {error}", file=sys.stderr)
        return 1
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != rendered:
            print("current-capability-status.md is stale; run scripts/generate-capability-status.py", file=sys.stderr)
            return 1
        print("capability registry and generated status are valid")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
