ALTER TABLE payment_sagas DROP CONSTRAINT IF EXISTS payment_saga_state_known;

ALTER TABLE payment_sagas ADD CONSTRAINT payment_saga_state_known CHECK (
    state IN (
        'INITIATED', 'FRAUD_CHECK_PENDING', 'FRAUD_REJECTED',
        'VOICE_VERIFICATION_PENDING', 'VOICE_VERIFICATION_TIMEOUT', 'VOICE_REJECTED',
        'VOICE_FALLBACK_PENDING', 'VOICE_FALLBACK_VERIFIED', 'VOICE_FALLBACK_FAILED',
        'FUNDS_RESERVING', 'FUNDS_RESERVATION_FAILED', 'FUNDS_RESERVED',
        'LEDGER_COMMITTING', 'UNKNOWN_EXTERNAL_STATUS', 'RECONCILIATION_REQUIRED',
        'MANUAL_REVIEW', 'LEDGER_COMMIT_FAILED', 'LEDGER_COMMITTED', 'COMPLETING',
        'COMPLETED', 'COMPENSATION_IN_PROGRESS', 'COMPENSATED', 'COMPENSATION_FAILED', 'FAILED'
    )
);
